### ISSUE TITLE
as.orthogonal function error

### ISSUE THREAD

**Issue by MamtaMohan** [RobinHankin/onion#20]
Hi,

I am using onion package to generate set orthogonal matrices from quaternions.

I tried to convert a quaternion to an equivalent orthogonal matrix. 

It gave me an error: Error in Re(q1) : non-numeric argument to function

I tried following sequence:
> q1 <- rquat(1)
> q1
An object of class "quaternion"
Slot "x":
         [,1]
Re -0.7134218
i  -1.0694264
j  -1.4381244
k  -0.6852207

> as.orthogonal(q1)
Error in Re(Q) : non-numeric argument to function

I tried example as mention in documentation as well. It also gave me an error.
> as.orthogonal(rquat(q1))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'z' in selecting a method for function 'Norm': error in evaluating the argument 'data' in selecting a method for function 'matrix': invalid arguments.

I would appreciate your response.

Mamta

**Comment by RobinHankin** [comment]
onion version 1.5-0:

> as.orthogonal(rquat(1))
           [,1]        [,2]       [,3]
[1,] -0.2519797 -0.38107978 -0.8895417
[2,] -0.1238721  0.92434173 -0.3608990
[3,]  0.9597718  0.01925015 -0.2801205
>

I strongly suspect that you didn't load the package correctly as the print
method was not invoked in the snippet you sent.

Robin




***@***.***>

**Comment by MamtaMohan** [comment]
Thank you.

That was the problem.

Mamta



________________________________
